### ISSUE TITLE
SyncContext.SynchronizeAsync() only works for the first time

### ISSUE THREAD

**Issue by verybox0** [Mimetis/SyncWinRT#14]
Dear Sir,

I just try to use this fantastic tool to sync with sqlite with sql server, the tutorial is great, however, when I try to run ContextModel at second time, it just ignored.

ContextModel cm = new ContextModel(documentId);
await cm.Sync(); 

My idea is pass different documentId to ContextModel, then when cm.Sync calls, it will just synchronize all the fields related to that document, but, only the first document form fields synchronized, the second document doesn't. Do I miss something?

this.SyncContext.AddScopeParameters("DocumentId",documentId.ToString());      

Thanks.

Box

**Comment by Mimetis** [comment]
The documentID change when you call back the sync method.
BUT the datetime of the "last time you sync" doesnt' change.
The rule is : "I sync every row SINCE the last date and the parameter filter"

If you want to make 2 sync (one for the first documentId, and one for the second documentId) you need to create two client database, for each documentId

Sebastien
