### ISSUE TITLE
Cant use on Mobile PCL Library

### ISSUE THREAD

**Issue by mpghelli** [Mimetis/SyncWinRT#26]
Hi.

I have a Xamarin.Forms App, that i wish to work offline with Sqlite.

I'm thinking about use SyncClient.SQLite to sync data between client and server, but when i try to reference it by nuget in a Mobile PCL Library (Xamarin Forms) it warning like incompatible library.

In git, Seems the library has been updated 6 months ago to be compatible with Mobile Apps, but in nuget the version appear date of 2014.

Anyone knows how can i use it on Xamarin.Forms properly?

Thank you

**Comment by johncdoherty** [comment]
@mpghelli I was successfully able to get this working within a Xamarin Forms PCL project. It was a while ago, and unfortunately I did it inline with the project I was working on, so it's not a completely seamless solution. I don't remember all the details, since I've made many custom changes since, but I'll attach some code from my local git repository at a version I think is good and it shouldn't be too difficult to get working from there. I believe there were some minor limitations with this approach, but here are some steps that I did: 

- I created a PCL library - SyncClient.PCL (no need for the other SyncClient.___ platform projects)
- I identified the classes that I would need access to in my Xamarin Forms PCL project and created interfaces for them. I put all of those in SyncClient.PCL. 
- I went through the SyncClient.Shared project and swapped the concrete class types for the interfaces
- In the Xamarin Forms PCL project, I referenced SyncClient.PCL and in my Droid/iOS platform projects I referenced both the SyncClient.PCL and SyncClient.Shared (very important that all platforms reference the Shared project) - I also get a feeling that you need to ensure that the compiler flag on the projects are set: __IOS__ __ANDROID__
- I then used dependency injection to register the interface to the types in the platform-specific projects and then resolved those types by the associated interface at runtime - you can use any framework you want, but I used FreshMvvm and the associated FreshTinyIoCContainer wrapper of TinyIoC. 
- Here's an example of how I registered the interfaces to the types (there may be a minor bug in this version)
```
			FreshTinyIoCContainer.Current.Register<IStorageHelper, StorageHelper>();
			FreshTinyIoCContainer.Current.Register<ISQLite, SQLiteClient>();
			FreshTinyIoCContainer.Current.Register<ISyncContext, SQLiteContext>().AsMultiInstance();
			FreshTinyIoCContainer.Current.Register<ISyncCacheController, CacheController>().AsMultiInstance();
			FreshTinyIoCContainer.Current.Register<ICacheControllerFactory, CacheControllerFactory>();
```
- Here's an example of how I initialized the context

```
			if (_syncContext == null)
			{
				var namedParameters =
					new FreshTinyIoC.NamedParameterOverloads()
				{
					{"schema",GetSchema()},
					{"scopeName", this.SyncScope},
					{"databasePath", this.DatabasePath},
					{"uri", this.ServiceURL},
					{"cookieContainer", null},
					{"uploadBatchSize", -1}
				};
				_syncContext =
					FreshTinyIoC.FreshTinyIoCContainer.Current.Resolve<ISyncContext>(namedParameters);
				_syncContext.CacheController.ControllerBehavior.Credentials = this.WebServiceCredential;
				_syncContext.CacheController.ControllerBehavior.AddScopeParameters("trandate", DateTime.Today.ToString());
				_syncContext.CacheController.ControllerBehavior.AddScopeParameters("drivercode", _settings.DriverCode);
				_syncContext.CacheController.ControllerBehavior.SerializationFormat =
					Microsoft.Synchronization.ClientServices.SerializationFormat.ODataJSON;
				await this.SyncAsync();

			}
```

I'm attaching the PCL and Shared projects. I can't recall if there are any other relevant details. Hopefully, this old code of mine leads you down a usable path. Code, as-is. Let me know if you run into issues.
Cheers,
John

[SyncClientXFPCL.zip](https://github.com/Mimetis/SyncWinRT/files/1072752/SyncClientXFPCL.zip)

**Comment by gentledepp** [comment]
Hi! John did explain the apporach quite well. 
We are also running this library on a Xamarin.Forms project.

@johncdoherty You wrote about a "local git repository" and that you made changes:
Could you please take your time to submit a PR with some explanations of what you did?

In general: I am sorry that we did not release a new NUGET package yet. I yould **strongly recommend** to everybody to clone and compile this library and use it as-is for now.

Reason:
We did some very important modifications since the last nuget release:
1) added a batch-upload support so your client wont get stuck in timeouts once the local changes exceeed some megabytes which would cause it to hang forever
2) switched to another SQLite library, as SQLitePCL from Microsoft has been abandoned and does **not work on Android 7 and above anymore** as it tries to use the Android system SQLite dll, which is not accepted anymore by Android for security reasons,
3) some other fixed I forgot

So please watch out!
I was not aware that there is still so much need for this library. :-|

**Comment by mpghelli** [comment]
Thank you guys
